### ISSUE TITLE
Can yugem be used outside of better-vim?

### ISSUE THREAD

**Issue by bjarneo** [vmarcosp/dotfiles#3]
Love your dotfiles. Trying to load it using nvchad -> lazyvim -> plugins without being able to activate it from either nvchad theming or setting colorscheme directly.

``` 
{
    dir = '~/path/to/forked/yugem',
    lazy = true,
    priority = 1000,
    config = function()
      require('yugem').setup({})
    end,
    init = function()
      vim.cmd("colorscheme yugem")
    end
  }
 ```

**Comment by vmarcosp** [comment]
Hey @bjarneo,

I'm glad you like it 😄. I think it's possible if you clone my dotfiles repo, link the yugem/ folder to your home, and set it up properly with lazy loading. What issues are you having with your approach?

By the way, I plan to release it as a Neovim theme compatible with any distro and setup, not just BetterVim.

**Comment by bjarneo** [comment]
Thank you for your reply. I am not sure what I did wrong yesterday, but it worked when I tested now. I guess it was something minor I did not notice. Really cool that you will release it. Keep it going!

**Comment by bjarneo** [comment]
FYI

Some errors like this. Disabled the theme and no error. Will have a glance at what it might be myself :)

```
Error executing vim.schedule lua callback: ...re/nvim/lazy/indent-blankline.nvim/lua/ibl/virt_text.lua:95: attempt to index a nil value                                                                         │
│ stack traceback:                                                                                                                                                                                                │
│         ...re/nvim/lazy/indent-blankline.nvim/lua/ibl/virt_text.lua:95: in function 'get'                                                                                                                       │
│         ...l/share/nvim/lazy/indent-blankline.nvim/lua/ibl/init.lua:426: in function ''                                                                                                                         │
│         vim/_editor.lua: in function <vim/_editor.lua:0>   
```

**Comment by bjarneo** [comment]
As it is indent-blankline, I just added this basic config to the loading of the theme, and seems like it is working https://github.com/lukas-reineke/indent-blankline.nvim?tab=readme-ov-file#background-color-indentation-guides
