### ISSUE TITLE
Btop color scheme

### ISSUE THREAD

**Issue by nitin88** [vmarcosp/dotfiles#4]
Hi,

I am not sure how you are running btop (inside nvim or outside).
Couldn't find the colorscheme file showcase the actual btop color scheme used.

Can you please export or share the actual Btop colorscheme?
May be exportToHTML works?

**Comment by nitin88** [comment]
@vmarcosp

**Comment by vmarcosp** [comment]
Hey, sorry for the delay @nitin88. Actually I'm not using any specific theme for btop, probably it's a combination of btop default colors + custom colors that I created for my kitty conf.
